<?php
/**
 * Plugin Name: Elementor Page Builder
 * Plugin URI: https://wordpress.org/plugins/elementor/
 *
 * Compatibility Description: Ensures compatibility with Elementor.
 *
 */

namespace wpCloud\StatelessMedia {

    if(!class_exists('wpCloud\StatelessMedia\Elementor')) {
        
        class Elementor extends ICompatibility {
            protected $id = 'elementor';
            protected $title = 'Elementor Page Builder';
            protected $constant = 'WP_STATELESS_COMPATIBILITY_ELEMENTOR';
            protected $description = 'Ensures compatibility with Elementor Page Builder. Sync css files generated by Elementor.';
            protected $plugin_file = 'elementor/elementor.php';

            public function module_init($sm){
                add_filter('set_url_scheme', array($this, 'sync_rewrite_url'), 10, 3);
            }

            public function sync_rewrite_url($url, $scheme, $orig_scheme){
                try{
                    if(strpos($url, 'elementor/') !== false){
                        $wp_uploads_dir = wp_get_upload_dir();
                        $name = str_replace($wp_uploads_dir['baseurl'] . '/', '', $url);
                        
                        if($name != $url){
                            $name = apply_filters( 'wp_stateless_file_name', $name);
                            do_action('sm:sync::syncFile', $name, $wp_uploads_dir['basedir'] . '/' . $name);
                            $url = ud_get_stateless_media()->get_gs_host() . '/' . $name;
                        }
                    }

                }
                catch(Exception $e){

                }
                return $url;
            }

        }

    }

}
