<?php
/**
 * Plugin Name: SiteOrigin CSS
 * Plugin URI: https://wordpress.org/plugins/so-css/
 *
 * Compatibility Description: Ensures compatibility with CSS files generated by SiteOrigin.
 *
 */

namespace wpCloud\StatelessMedia {

    if (!class_exists('wpCloud\StatelessMedia\SOCSS')) {
        
        class SOCSS extends ICompatibility {
            protected $id = 'so-css';
            protected $title = 'SiteOrigin CSS';
            protected $constant = 'WP_STATELESS_COMPATIBILITY_SOCSS';
            protected $description = 'Ensures compatibility with CSS files generated by SiteOrigin.';
            protected $plugin_constant = 'SOCSS_VERSION';

            public function module_init($sm){
                add_filter( 'set_url_scheme', array( $this, 'set_url_scheme' ), 20, 3 );

            }

            /**
             * Change Upload BaseURL when CDN Used.
             *
             * @param $data
             * @return mixed
             */
            public function set_url_scheme( $url, $scheme, $orig_scheme ) {
                $position = strpos($url, 'so-css/');
                if( $position !== false ){
                    $upload_data = wp_upload_dir();
                    $name = substr($url, $position);
                    $absolutePath = $upload_data['basedir'] . '/' .  $name;
                    do_action( 'sm:sync::syncFile', $name, $absolutePath);
                    $url = ud_get_stateless_media()->get_gs_host() . '/' . $name;
                }
                return $url;
            }

        }

    }

}
