<div class="wrap">
    <h2>Menu Page Title</h2>
    <div class="description">This is description of the page.</div>
    <?php settings_errors(); ?> 

    <h2 class="nav-tab-wrapper">  
        <a href="#stless_settings_tab" class="stless_setting_tab nav-tab active">Settings</a>  
        <a href="#stless_supports_tab" class="stless_setting_tab nav-tab">Support</a>  
    </h2>  

    <div class="stless_settings">
        <div id="stless_settings_tab" class="stless_settings_content active">
            <form method="post" action="options.php"> 
                <table class="form-table">
                    <tbody>
                        <tr>
                            <th scope="row">General</th>
                            <td>
                                <fieldset>
                                    <legend class="screen-reader-text"><span>General</span></legend>
                                    <h4>Mode: </h4>
                                    <p class="sm-mode">
                                        <label for="sm_mode_disabled"><input id="sm_mode_disabled" type="radio" name="sm[mode]" value="disabled">Disabled<small class="description">Disable Stateless Media.</small></label>
                                    </p>
                                    <p class="sm-mode">
                                        <label for="sm_mode_backup"><input id="sm_mode_backup" type="radio" name="sm[mode]" value="backup">Backup<small class="description">Push media files to Google Storage but keep using local ones.</small></label>
                                    </p>
                                    <p class="sm-mode">
                                        <label for="sm_mode_cdn"><input id="sm_mode_cdn" checked="checked" type="radio" name="sm[mode]" value="cdn">CDN<small class="description">Push media files to Google Storage and use them directly from there.</small></label>
                                    </p>
                                    <p class="sm-mode">
                                        <label for="sm_mode_stateless"><input id="sm_mode_stateless" type="radio" name="sm[mode]" value="stateless">Stateless<small class="description">Uploads and serves your media library items to and from GCS. Your local copy is removed.</small></label>
                                    </p>
                                    <hr>

                                    <h4>File URL Replacement: </h4>
                                    <p class="sm-file-url">
                                        <select name="sm_file_url" id="sm_file_url">
                                            <option value="enable" selected="selected">Enable</option>
                                            <option value="disable">Disable</option>
                                        </select>
                                    </p>
                                    <p class="description">Scans post content and meta during presentation and replaces local media file urls with GCS urls. This setting does not modify your database.</p>
                                    <hr>

                                    <h4>Dynamic Image Support: </h4>
                                    <p class="dynamic_img_sprt">
                                        <select name="dynamic_img_sprt" id="dynamic_img_sprt">
                                            <option value="enable" selected="selected">Enable</option>
                                            <option value="disable">Disable</option>
                                        </select>
                                    </p>
                                    <p class="description">Upload image thumbnails generated by your theme and plugins that do not register media objects with the media library.</p>
                                    <hr>                    
                                </fieldset>
                            </td>
                        </tr>
                        
                        <tr>
                            <th scope="row">Google Cloud Storage (GCS)</th>
                            <td>
                                <fieldset>
                                    <legend class="screen-reader-text"><span>Google Cloud Storage (GCS)</span></legend>
                                    <h4>Bucket: </h4>
                                    <p>
                                        <label for="bucket_name">
                                            <input name="bucket_name" type="text" id="bucket_name" class="regular-text ltr">
                                        </label>
                                    </p>
                                    <p class="description">The name of the GCS bucket.</p>
                                    <hr>       

                                    <h4>Bucket Folder: </h4>
                                    <p>
                                        <label for="bucket_folder_name">
                                            <input name="bucket_folder_name" type="text" id="bucket_folder_name" class="regular-text ltr">
                                        </label>
                                    </p>
                                    <p class="description">If you would like files to be uploaded into a particular folder within the bucket, define that path here.</p>
                                    <hr>

                                    <h4>Service Account JSON: </h4>
                                    <p>
                                        <label for="service_account_json">
                                            <textarea name="service_account_json" type="text" id="service_account_json" class="regular-text ltr"></textarea>
                                        </label>
                                    </p>
                                    <p class="description">Private key in JSON format for the service account WP-Stateless will use to connect to your Google Cloud project and bucket.</p>
                                    <hr>

                                    <h4>Cache-Control: </h4>
                                    <p>
                                        <select name="gcs_cache_control" id="gcs_cache_control">
                                            <option value="enable">Enable</option>
                                            <option value="disable" selected="selected">Disable</option>
                                        </select>
                                    </p>

                                    <p>
                                        <label for="gcs_cache_control_text">
                                            <input name="gcs_cache_control_text" type="text" id="gcs_cache_control_text" class="regular-text ltr" value="public, max-age=36000, must-revalidate">
                                        </label>
                                    </p>
                                    <p class="description">Control the default cache control assigned by GCS.</p>
                                    <hr>

                                    <h4>Delete GCS File: </h4>
                                    <p>
                                        <select name="gcs_delete_file" id="gcs_delete_file">
                                            <option value="enable" selected="selected">Enable</option>
                                            <option value="disable">Disable</option>
                                        </select>
                                    </p>
                                    <p class="description">Delete the GCS file when the file is deleted from WordPress.</p>
                                </fieldset>
                            </td>
                        </tr>  
                        <tr>
                            <th scope="row">File URL group</th>
                            <td>
                                <fieldset>
                                    <legend class="screen-reader-text"><span>File URL group</span></legend>
                                    <h4>Preview: </h4>
                                    <p>
                                        <label for="file_url_grp_preview">
                                            <input name="file_url_grp_preview" type="text" id="file_url_grp_preview" class="regular-text ltr" value="https://www." readonly="readonly">
                                        </label>
                                    </p>
                                    <p class="description">An example file url utilizing all configured settings.</p>
                                    <hr>        

                                    <h4>Domain: </h4>
                                    <p>
                                        <label for="bucket_folder_name">
                                            <input name="bucket_folder_name" type="text" id="bucket_folder_name" class="regular-text ltr" placeholder="storage.googleapis.com">
                                        </label>
                                    </p>
                                    <p class="description">Replace the default GCS domain with your own custom domain. This will require you to <a href="https://cloud.google.com/storage/docs/xml-api/reference-uris#cname" target="_blank">configure a CNAME</a>.</p>
                                    <hr>

                                    <h4>HTTPS: </h4>
                                    <p>
                                        <select name="https_enable" id="https_enable">
                                            <option value="enable" selected="selected">Enable</option>
                                            <option value="disable">Disable</option>
                                        </select>
                                    </p>
                                    <p class="description">If you are using a custom domain and you do not have SSL configured, you will need to disable HTTPS.</p>
                                    <hr>

                                    <h4>Organization: </h4>
                                    <p>
                                        <select name="org_url_grp" id="org_url_grp">
                                            <option value="enable" selected="selected">Enable</option>
                                            <option value="disable">Disable</option>
                                        </select>
                                    </p>
                                    <p class="description">Organize uploads into year and month based folders.</p>

                                    <hr>
                                    <h4>Cache-Busting: </h4>
                                    <p>
                                        <select name="cache_busting" id="cache_busting">
                                            <option value="enable" selected="selected">Enable</option>
                                            <option value="disable">Disable</option>
                                        </select>
                                    </p>
                                    <p class="description">Prepends a random set of numbers and letters to the filename. This is useful for preventing caching issues when uploading files that have the same filename.</p>
                                </fieldset>
                            </td>
                        </tr> 
                        <tr>
                            <th scope="row">Thumbnails</th>
                            <td>
                                <fieldset>
                                    <legend class="screen-reader-text"><span>Thumbnails</span></legend>
                                    <p>
                                        <label for="file_url_grp_preview">
                                            <button class="button">Notify Me When Available!</button>
                                        </label>
                                    </p>
                                    <p class="description">Coming soon! Delegate thumbnail generation to the cloud and only when needed.</p>
                                </fieldset>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">Synchronization</th>
                            <td>
                                <fieldset>
                                    <legend class="screen-reader-text"><span>Thumbnails</span></legend>
                                    <p class="description">Coming soon! Synchronize any amount of existing media across WordPress and GCS without the need of cron jobs or leaving your browser open.</p>
                                </fieldset>
                            </td>
                        </tr> 
                        <tr>
                            <th scope="row">Compression</th>
                            <td>
                                <fieldset>
                                    <legend class="screen-reader-text"><span>Thumbnails</span></legend>
                                    <p class="description">Coming soon! Optimize your image media with the perfect balance in quality and file size.</p>
                                </fieldset>
                            </td>
                        </tr>  
                    </tbody>
                </table>


                <?php submit_button(); ?> 
            </form> 
        </div>

        <div id="stless_supports_tab" class="stless_settings_content">
            <p>Keep your project moving forward and unhindered with access to our support team. With a support plan, you will have access to our support and engineering team to ask questions and receive assistance with your issues. You will also receive technical support, in-depth troubleshooting, and we’ll even log into your website to assist with resolving issues.</p>


        </div>
    </div>

</div>